# Generated by Django 4.1.5 on 2023-03-26 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming_app', '0011_contactus_model_alter_farmercomplain_model_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 26, 11, 53, 18, 630718)),
        ),
        migrations.AlterField(
            model_name='farmercomplain_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 26, 11, 53, 18, 629640)),
        ),
        migrations.AlterField(
            model_name='farmertips_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 26, 11, 53, 18, 630718)),
        ),
        migrations.AlterField(
            model_name='feedback_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 26, 11, 53, 18, 630718)),
        ),
        migrations.AlterField(
            model_name='retailer_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 26, 11, 53, 18, 629640)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 26, 11, 53, 18, 629640)),
        ),
    ]
